# Generated by Django 6.0.4 on 2026-04-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UdinSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveIntegerField(blank=True, null=True)),
                ('udin', models.CharField(blank=True, default='', max_length=60)),
                ('mrn', models.CharField(blank=True, default='', max_length=30)),
                ('firm', models.CharField(blank=True, default='', max_length=255)),
                ('document_type', models.CharField(blank=True, default='', max_length=120)),
                ('document_sub_type', models.CharField(blank=True, default='', max_length=120)),
                ('other_doc', models.CharField(blank=True, default='', max_length=120)),
                ('document_description', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_signing_of_document', models.CharField(blank=True, default='', max_length=30)),
                ('ay_fy', models.CharField(blank=True, default='', max_length=40)),
                ('created_date_time', models.CharField(blank=True, default='', max_length=60)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('particulars_1', models.CharField(blank=True, default='', max_length=180)),
                ('figures_values_1', models.CharField(blank=True, default='', max_length=180)),
                ('particulars_2', models.CharField(blank=True, default='', max_length=180)),
                ('figures_values_2', models.CharField(blank=True, default='', max_length=180)),
                ('particulars_3', models.CharField(blank=True, default='', max_length=180)),
                ('figures_values_3', models.CharField(blank=True, default='', max_length=180)),
                ('particulars_4', models.CharField(blank=True, default='', max_length=180)),
                ('figures_values_4', models.CharField(blank=True, default='', max_length=180)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_udin_source_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'udins_source',
                'ordering': ['-created_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UdinSourceHeaderMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=40, unique=True)),
                ('mapping_json', models.JSONField(default=dict)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_udin_source_header_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'udins_source_header_maps',
            },
        ),
    ]
