# Generated by Django 6.0.4 on 2026-04-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udins_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udinsource',
            name='udin',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
