# Generated by Django 6.0.4 on 2026-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udins_source', '0002_alter_udinsource_udin'),
    ]

    operations = [
        migrations.AddField(
            model_name='udinsource',
            name='copied_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='udinsource',
            name='copied_to_udins',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
