# Generated by Django 6.0.4 on 2026-06-14 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udins_source', '0003_udinsource_copied_on_udinsource_copied_to_udins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='udinsource',
            name='udin',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='udinsource',
            constraint=models.UniqueConstraint(fields=('udin',), name='uq_udins_source_udin'),
        ),
    ]
