# Generated by Django 6.0.4 on 2026-04-14 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_desc', models.CharField(max_length=150)),
                ('grade_code', models.CharField(max_length=4, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['grade_desc'],
            },
        ),
    ]
