# Generated by Django 6.0.4 on 2026-08-27 09:01

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBankCashAc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ac', models.CharField(max_length=15, unique=True)),
                ('fb_code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'source_bank_cash_acs',
                'ordering': ['source_ac'],
            },
        ),
        migrations.CreateModel(
            name='BankTransactionSourceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(max_length=6)),
                ('ob', models.FloatField(blank=True, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('cb', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Coalesce(models.F('ob'), models.Value(0.0)), '+', django.db.models.functions.comparison.Coalesce(models.F('debit'), models.Value(0.0))), '-', django.db.models.functions.comparison.Coalesce(models.F('credit'), models.Value(0.0))), output_field=models.FloatField())),
                ('cb_from_statement', models.FloatField(blank=True, null=True)),
                ('check_diff', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Coalesce(models.F('ob'), models.Value(0.0)), '+', django.db.models.functions.comparison.Coalesce(models.F('debit'), models.Value(0.0))), '-', django.db.models.functions.comparison.Coalesce(models.F('credit'), models.Value(0.0))), '-', django.db.models.functions.comparison.Coalesce(models.F('cb_from_statement'), models.Value(0.0))), output_field=models.FloatField())),
                ('account_type', models.CharField(blank=True, max_length=2, null=True)),
                ('source_ac', models.ForeignKey(db_column='source_ac', on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='bank_transactions.sourcebankcashac', to_field='source_ac')),
            ],
            options={
                'db_table': 'bank_transactions_source_summary',
                'ordering': ['source_ac', 'ym'],
            },
        ),
        migrations.CreateModel(
            name='BankTransactionSourceOb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(max_length=5)),
                ('ob', models.FloatField(blank=True, null=True)),
                ('source_ac', models.OneToOneField(db_column='source_ac', on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance', to='bank_transactions.sourcebankcashac', to_field='source_ac')),
            ],
            options={
                'db_table': 'bank_transactions_source_ob',
                'ordering': ['source_ac'],
            },
        ),
        migrations.CreateModel(
            name='BankTransactionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField()),
                ('narration', models.CharField(blank=True, max_length=1000, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('net_debit', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Coalesce(models.F('debit'), models.Value(0.0)), '-', django.db.models.functions.comparison.Coalesce(models.F('credit'), models.Value(0.0))), output_field=models.FloatField())),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('value_date', models.DateField()),
                ('tran_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fb_mapped', models.CharField(blank=True, max_length=10, null=True)),
                ('posting_fb', models.CharField(blank=True, max_length=10, null=True)),
                ('gl_account', models.CharField(blank=True, max_length=150, null=True)),
                ('main_analysis', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_analysis', models.CharField(blank=True, max_length=50, null=True)),
                ('tertiary_analysis', models.CharField(blank=True, max_length=50, null=True)),
                ('ym', models.CharField(blank=True, max_length=5, null=True)),
                ('account_type', models.CharField(blank=True, max_length=2, null=True)),
                ('source_ac', models.ForeignKey(db_column='source_ac', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bank_transactions.sourcebankcashac', to_field='source_ac')),
            ],
            options={
                'db_table': 'bank_transactions_source',
                'ordering': ['source_ac', 'tran_date'],
            },
        ),
    ]
