# Generated by Django 6.0.4 on 2026-08-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionsource',
            name='closing_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
    