# Generated by Django 6.0.4 on 2026-08-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0002_banktransactionsource_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionsourcesummary',
            name='ym',
            field=models.CharField(max_length=5),
        ),
    ]

    