# Generated by Django 6.0.4 on 2026-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0003_alter_banktransactionsourcesummary_ym'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcebankcashac',
            name='account_type',
            field=models.CharField(
                blank=True,
                default='',
                max_length=2,
                choices=[
                    ('SB', 'Savings Bank'),
                    ('CA', 'Current Account'),
                    ('CC', 'Credit Card'),
                    ('CD', 'Cash Credit'),
                    ('OD', 'Overdraft'),
                ],
            ),
        ),
        migrations.AddField(
            model_name='sourcebankcashac',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
    