# Generated by Django 6.0.4 on 2026-08-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0004_sourcebankcashac_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcebankcashac',
            name='fb_code',
            field=models.CharField(max_length=5),
        ),
    ]
    