# Generated by Django 6.0.4 on 2026-08-31 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0005_alter_sourcebankcashac_fb_code'),
        ('fiscal_years', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_file', models.FileField(upload_to='bank_statements/%Y/%m/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_uploads', to='fiscal_years.fiscalyear')),
                ('source_ac', models.ForeignKey(db_column='source_ac', on_delete=django.db.models.deletion.PROTECT, related_name='statement_uploads', to='bank_transactions.sourcebankcashac', to_field='source_ac')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_statement_uploads',
                'ordering': ['-uploaded_on'],
            },
        ),
        migrations.AddField(
            model_name='banktransactionsourcesummary',
            name='statement_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_rows', to='bank_transactions.bankstatementupload'),
        ),
    ]
    