# Generated by Django 6.0.4 on 2026-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0006_bankstatementupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_code', models.CharField(max_length=20, unique=True)),
                ('fb_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('entity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fbs',
                'ordering': ['fb_code'],
                'managed': False,
            },
        ),
    ]

    