# Generated by Django 6.0.4 on 2026-09-02 09:05

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


def copy_ob_to_debit(apps, schema_editor):
    BankTransactionSourceOb = apps.get_model("bank_transactions", "BankTransactionSourceOb")
    BankTransactionSourceOb.objects.filter(ob__isnull=False).update(ob_debit=models.F("ob"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0007_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionsourceob',
            name='ob_credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransactionsourceob',
            name='ob_debit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(copy_ob_to_debit, noop_reverse),
        migrations.RemoveField(
            model_name='banktransactionsourceob',
            name='ob',
        ),
        migrations.AddField(
            model_name='banktransactionsourceob',
            name='ob',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Coalesce(models.F('ob_debit'), models.Value(0.0)), '-', django.db.models.functions.comparison.Coalesce(models.F('ob_credit'), models.Value(0.0))), output_field=models.FloatField()),
        ),
    ]
