from django.urls import path

from engagements import views

urlpatterns = [
    path("work-areas/", views.work_area_hub, name="work_area_hub"),
    path(
        "work-areas/by-engagement/",
        views.work_area_pick_engagement,
        name="work_area_pick_engagement",
    ),
    path(
        "work-areas/by-division/",
        views.work_area_pick_division,
        name="work_area_pick_division",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/",
        views.engagement_work_areas,
        name="engagement_work_areas",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/new/",
        views.engagement_work_area_create,
        name="engagement_work_area_create",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/notes/",
        views.engagement_work_area_notes_list,
        name="engagement_work_area_notes_list",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:pk>/edit/",
        views.engagement_work_area_edit,
        name="engagement_work_area_edit",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/schedule-rows/",
        views.engagement_work_area_schedule,
        name="engagement_work_area_schedule",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/schedule-rows/new/",
        views.engagement_work_area_schedule_create,
        name="engagement_work_area_schedule_create",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/schedule-rows/<int:pk>/edit/",
        views.engagement_work_area_schedule_edit,
        name="engagement_work_area_schedule_edit",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/assignments/",
        views.engagement_work_area_assignments,
        name="engagement_work_area_assignments",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/assignments/new/",
        views.engagement_work_area_assignment_create,
        name="engagement_work_area_assignment_create",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/assignments/<int:pk>/edit/",
        views.engagement_work_area_assignment_edit,
        name="engagement_work_area_assignment_edit",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/documents/",
        views.engagement_work_area_documents,
        name="engagement_work_area_documents",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/documents/<int:pk>/download/",
        views.engagement_work_area_document_download,
        name="engagement_work_area_document_download",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/queries/",
        views.engagement_work_area_queries,
        name="engagement_work_area_queries",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/queries/<int:query_pk>/attachments/<int:pk>/download/",
        views.engagement_query_attachment_download,
        name="engagement_query_attachment_download",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/status-remarks/",
        views.engagement_work_area_status_remarks,
        name="engagement_work_area_status_remarks",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/",
        views.engagement_division_work_areas,
        name="engagement_division_work_areas",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/new/",
        views.engagement_division_work_area_create,
        name="engagement_division_work_area_create",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/notes/",
        views.engagement_division_work_area_notes_list,
        name="engagement_division_work_area_notes_list",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:pk>/edit/",
        views.engagement_division_work_area_edit,
        name="engagement_division_work_area_edit",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/schedule-rows/",
        views.engagement_division_work_area_schedule,
        name="engagement_division_work_area_schedule",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/schedule-rows/new/",
        views.engagement_division_work_area_schedule_create,
        name="engagement_division_work_area_schedule_create",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/schedule-rows/<int:pk>/edit/",
        views.engagement_division_work_area_schedule_edit,
        name="engagement_division_work_area_schedule_edit",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/documents/",
        views.engagement_division_work_area_documents,
        name="engagement_division_work_area_documents",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/assignments/",
        views.engagement_division_work_area_assignments,
        name="engagement_division_work_area_assignments",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/assignments/new/",
        views.engagement_division_work_area_assignment_create,
        name="engagement_division_work_area_assignment_create",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/assignments/<int:pk>/edit/",
        views.engagement_division_work_area_assignment_edit,
        name="engagement_division_work_area_assignment_edit",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/documents/<int:pk>/download/",
        views.engagement_division_work_area_document_download,
        name="engagement_division_work_area_document_download",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/queries/",
        views.engagement_division_work_area_queries,
        name="engagement_division_work_area_queries",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/queries/<int:query_pk>/attachments/<int:pk>/download/",
        views.engagement_division_query_attachment_download,
        name="engagement_division_query_attachment_download",
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/status-remarks/",
        views.engagement_division_work_area_status_remarks,
        name="engagement_division_work_area_status_remarks",
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/periods/",
        views.engagement_work_area_schedule,
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/periods/new/",
        views.engagement_work_area_schedule_create,
    ),
    path(
        "engagements/<int:engagement_pk>/work-areas/<int:work_area_pk>/periods/<int:pk>/edit/",
        views.engagement_work_area_schedule_edit,
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/periods/",
        views.engagement_division_work_area_schedule,
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/periods/new/",
        views.engagement_division_work_area_schedule_create,
    ),
    path(
        "divisions/<int:division_pk>/work-areas/<int:work_area_pk>/periods/<int:pk>/edit/",
        views.engagement_division_work_area_schedule_edit,
    ),
]
