# Generated by Django 6.0.4 on 2026-04-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
