# Generated by Django 6.0.4 on 2026-04-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_client_client_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
