# Generated by Django 6.0.4 on 2026-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_client_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='classification',
            field=models.CharField(choices=[('private_limited_company', 'Private Limited Company'), ('public_limited_company', 'Public Limited Company'), ('listed_company', 'Listed Company'), ('llp', 'LLP'), ('partnership_firm', 'Partnership Firm'), ('sole_propreitprship', 'Sole-propreitprship'), ('trust', 'Trust'), ('individual', 'Individual'), ('huf', 'HUF'), ('aop', 'AOP'), ('others', 'Others')], max_length=30),
        ),
    ]
