# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0009_clienttaxprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address_1",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="client",
            name="address_2",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="client",
            name="area",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="client",
            name="city_state_pincode",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="client",
            name="contact_person",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="client",
            name="mail_id",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
