# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0010_client_gst_invoicing_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="billing_gstn",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
