# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0011_client_billing_gstn"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="state",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="client",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
