# Generated by Django 6.0.4 on 2026-04-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0012_client_state_pincode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_name", models.CharField(max_length=150)),
                ("account_code", models.CharField(max_length=30, unique=True)),
                ("plbs", models.CharField(choices=[("PL", "PL"), ("BS", "BS")], max_length=2)),
                (
                    "plbs_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("INCOME", "Income"),
                            ("EXPENSES", "Expenses"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_chart_of_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chart_of_accounts",
                "ordering": ["account_code", "account_name"],
            },
        ),
    ]
