# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0013_chartofaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="invoice_tax_type",
            field=models.CharField(
                choices=[("GST", "GST (CGST + SGST)"), ("IGST", "IGST")],
                default="GST",
                help_text="GST: 9% CGST and 9% SGST on taxable value. IGST: 18% on taxable value.",
                max_length=8,
            ),
        ),
    ]
