# Generated by Django 6.0.4

import django.db.models.deletion
import sales.clients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0017_client_additional_mail_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=sales.clients.models._client_document_upload_to
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "document_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short label, e.g. MOA, AOA, Board resolution.",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="config.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_client_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "client_documents",
                "ordering": ["document_label", "original_filename", "pk"],
            },
        ),
    ]
