# Generated by Django 6.0.4 on 2026-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='old_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=4),
        ),
    ]
