"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY in .env for any real deployment. The fallback below is only
# for first-time local setup and must never be used once this is hosted.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-@bo5kob^giztbueh4b8z6=3&jg&-n+*xh3o2tii88=1lnn5z$0',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() in ('1', 'true', 'yes', 'on')

# Comma-separated list in .env, e.g. DJANGO_ALLOWED_HOSTS=192.168.1.50,erp.local
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sales.clients.apps.ClientsConfig',
    'sales.services.apps.ServicesConfig',
    'sales.udins_source.apps.UdinsSourceConfig',
    'sales.udins.apps.UdinsConfig',
    'sales.invoices.apps.InvoicesConfig',
    'engagements.apps.EngagementsConfig',
    'gl.fiscal_years.apps.FiscalYearsConfig',
    'gl.chart_of_accounts.apps.ChartOfAccountsConfig',
    'gl.journal.apps.JournalConfig',
    'hr.teams.apps.TeamsConfig',
    'hr.grades.apps.GradesConfig',
    'hr.qualifications.apps.QualificationsConfig',
    # After contrib.auth so config.admin can replace the default User admin.
    'config.apps.ConfigConfig',
    # After all business model apps (registry imports their models).
    'audit.apps.AuditConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'audit.middleware.AuditUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'engagements.context_processors.active_time_session',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'jk_erp'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        # Use 127.0.0.1 by default: "localhost" on Windows can stall on IPv6 (::1)
        # when Postgres only listens on IPv4.
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5433'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Leading slash required: relative URLs (e.g. "static/…") resolve under the current
# path ("/setup/sales/static/…") and miss Django's static file routes ("/static/…").
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# User uploads (engagement documentation attachments, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / 'media'

# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Printed / PDF invoice preview (A4). Override in local .env or split settings if needed.
INVOICE_LETTERHEAD = {
    "firm_name": "M.S. JAGANNATHAN & N. KRISHNASWAMI",
    "firm_subtitle": "Chartered Accountants",
    "address_line_1": "G5, Abirami Apartments, 14 VOC Road, Cantonment, Trichy 620001",
    "address_line_2": "26/9, Mayor Shivashanmugam Street, Old Washermenpet, Chennai 600021",
    "phone": "9381721405",
    "email": "srinivasan.k@msjandnk.in",
    "bank_ifsc": "HDFC0001271",
    "bank_account_no": "50200117154042",
    "bank_account_label": "Current Account",
    "bank_pay_instruction": "Please pay to the credit of the following account.",
    "bank_holder": "M.S.Jagannathan & N.Krishnaswami",
    "signatory_prefix": "For M.S.Jagannathan & N.Krishnaswami",
    "signatory_role": "Partner",
    "authorised_signatory_name": "Srinivasan Krishnaswami",
    "firm_pan": "AADFM3546J",
    "firm_gstn": "33AADFM3546J2ZB",
    "computer_generated_note": (
        "Computer generated invoice and does not require signature"
    ),
}

# Email — Zoho (smtppro.zoho.com). Put secrets in the project root ``.env``; see ``.env.example``.
# Django's default connection (e.g. ``manage.py sendtestemail``) uses these variables.
# Team assignment mail uses ``SmtpMailSettings`` in the database: Setup → Mail in the web UI.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtppro.zoho.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))


def _env_bool(key: str, default: str) -> bool:
    return os.environ.get(key, default).strip().lower() in ("1", "true", "yes", "on")


_tls_raw = os.environ.get("EMAIL_USE_TLS", "").strip()
_ssl_raw = os.environ.get("EMAIL_USE_SSL", "").strip()
if _tls_raw:
    EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", "false")
else:
    EMAIL_USE_TLS = EMAIL_PORT != 465
if _ssl_raw:
    EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", "false")
else:
    EMAIL_USE_SSL = EMAIL_PORT == 465

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
_default_from = (INVOICE_LETTERHEAD.get("email") or "").strip()
DEFAULT_FROM_EMAIL = (os.environ.get("DEFAULT_FROM_EMAIL") or _default_from or "").strip()
SERVER_EMAIL = (os.environ.get("SERVER_EMAIL") or DEFAULT_FROM_EMAIL or "").strip()
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "30"))
