# Generated by Django 6.0.4 on 2026-04-15 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10)),
                ('model_label', models.CharField(db_index=True, help_text='Django model label, e.g. config.Client', max_length=120)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
