TIME_SESSION_STATUS_OPEN = "open"
TIME_SESSION_STATUS_CLOSED = "closed"
TIME_SESSION_STATUS_ADJUSTED = "adjusted"

TIME_SESSION_CLOSE_SOURCE_USER_STOP = "user_stop"
TIME_SESSION_CLOSE_SOURCE_AUTO_SWITCH = "auto_switch"
TIME_SESSION_CLOSE_SOURCE_AUTO_DAY_CLOSE = "auto_day_close"
TIME_SESSION_CLOSE_SOURCE_ADMIN_FIX = "admin_fix"
