# Generated by Django 6.0.4 on 2026-04-14 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_desc', models.CharField(max_length=150)),
                ('service_code', models.CharField(max_length=10, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['service_desc'],
            },
        ),
    ]
