# Generated by Django 6.0.4 on 2026-04-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
