# Generated by Django 6.0.4 on 2026-04-15 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_desc', models.CharField(max_length=150)),
                ('qualification_code', models.CharField(max_length=4, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qualifications',
                'ordering': ['qualification_desc'],
            },
        ),
    ]
