# Generated by Django 6.0.4 on 2026-04-29 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0013_chartofaccount'),
        ('fiscal_years', '0001_initial'),
        ('services', '0002_alter_service_service_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=40)),
                ('inv_taxable_value', models.DecimalField(decimal_places=2, help_text='Invoice taxable value (Inv Tv).', max_digits=14)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inv_gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='config.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fiscal_years.fiscalyear')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='services.service')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('client', 'invoice_no'), name='uq_invoice_client_invoice_no')],
            },
        ),
    ]
