# Generated by Django 6.0.4 on 2026-04-29 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial_invoice'),
        ('udins', '0007_certificationfeerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='udin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='udins.udin'),
        ),
    ]
