# Generated by Django 6.0.4 on 2026-04-29 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_chartofaccount'),
        ('fiscal_years', '0001_initial'),
        ('invoices', '0002_invoice_udin'),
        ('services', '0002_alter_service_service_code'),
        ('udins', '0007_certificationfeerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('udin__isnull', False)), fields=('udin',), name='uq_invoice_udin_when_set'),
        ),
    ]
