# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_udin_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_no", models.PositiveSmallIntegerField()),
                ("line_type", models.CharField(max_length=16)),
                ("line_base_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=6)),
                ("item_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_lines",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_lines",
                "ordering": ["invoice_id", "line_no"],
            },
        ),
    ]
