# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_invoiceline"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="narration",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional text printed on the invoice (e.g. scope or reference).",
            ),
        ),
    ]
