# Generated by Django 6.0.4 on 2026-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_inv_udin_map_remove_invoice_udin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('authorised', 'Authorised')], db_index=True, default='fresh', help_text='Fresh when created; set to Authorised before posting to GL.', max_length=20),
        ),
    ]
