# Generated by Django 6.0.4 on 2026-04-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_journal', '0003_remove_glheader_amount'),
        ('invoices', '0007_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='posted_gl_header',
            field=models.OneToOneField(blank=True, help_text='Authorised GL voucher created when this invoice was posted from Sales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_from_invoice', to='gl_journal.glheader'),
        ),
    ]
