# Generated by Django 6.0.4 on 2026-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_posted_gl_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('authorised', 'Authorised')], db_index=True, default='fresh', help_text='Fresh when created; bulk post from the invoice list creates GL and sets Authorised.', max_length=20),
        ),
    ]
