# Generated by Django 6.0.4 on 2026-04-29 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0015_salesledgersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlHeader',
            fields=[
                ('rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_date', models.DateField(db_index=True)),
                ('tran_id', models.CharField(db_index=True, help_text='Business transaction id (document / batch id within source).', max_length=40)),
                ('source', models.CharField(choices=[('Sales', 'Sales'), ('Purchases', 'Purchases'), ('Payroll', 'Payroll'), ('FA', 'FA'), ('JV', 'JV'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Other', 'Other')], db_index=True, max_length=20)),
                ('narration', models.TextField(blank=True, default='')),
                ('debit_sum', models.DecimalField(decimal_places=2, default=0, help_text='Total debits on lines.', max_digits=18)),
                ('credit_sum', models.DecimalField(decimal_places=2, default=0, help_text='Total credits on lines.', max_digits=18)),
                ('net_debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit minus credit (signed).', max_digits=18)),
                ('ym', models.CharField(blank=True, db_index=True, default='', help_text='Reporting month key, e.g. M YYYY MM as stored by your convention.', max_length=12)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('authorised', 'Authorised')], db_index=True, default='fresh', max_length=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_gl_headers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gl_header',
                'ordering': ['-tran_date', '-rec_id'],
            },
        ),
        migrations.CreateModel(
            name='GlLine',
            fields=[
                ('rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('line_description', models.CharField(blank=True, default='', max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit minus credit for this line.', max_digits=18)),
                ('ym', models.CharField(blank=True, db_index=True, default='', help_text='Line reporting month (M YYYY MM as stored).', max_length=12)),
                ('rm_or', models.CharField(blank=True, db_index=True, default='', help_text='RM / OR month key (M YYYY MM as stored).', max_length=12)),
                ('value_ym', models.CharField(blank=True, db_index=True, default='', help_text='Value month (M YYYY MM as stored).', max_length=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_code', on_delete=django.db.models.deletion.PROTECT, related_name='gl_lines', to='config.chartofaccount', to_field='account_code')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gl_journal.glheader')),
            ],
            options={
                'db_table': 'gl_line',
                'ordering': ['header', 'line_no'],
                'constraints': [models.UniqueConstraint(fields=('header', 'line_no'), name='gl_line_header_line_no_uniq')],
            },
        ),
    ]
