# Generated by Django 6.0.4 on 2026-04-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_years', '0001_initial'),
        ('gl_journal', '0003_remove_glheader_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative signed balance for this FY and account (Dr +, Cr −).', max_digits=18)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tb_table_rows', to='fiscal_years.fiscalyear')),
            ],
            options={
                'db_table': 'tb_table',
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'account_code'), name='tb_table_fy_account_uniq')],
            },
        ),
    ]
