# Generated by Django 6.0.4 on 2026-04-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_years', '0001_initial'),
        ('gl_journal', '0004_tb_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTableMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField(db_index=True, help_text='First calendar day of the posting month.')),
                ('period_to', models.DateField(help_text='Last calendar day of the posting month.')),
                ('account_code', models.CharField(db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Net signed amount for this FY, month, and account.', max_digits=18)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tb_table_month_rows', to='fiscal_years.fiscalyear')),
            ],
            options={
                'db_table': 'tb_table_month',
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'period_from', 'account_code'), name='tb_table_month_fy_period_account_uniq')],
            },
        ),
    ]
