# Generated by Django 6.0.4 on 2026-04-14 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('called_as', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberRollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_team_member_roll_periods', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_periods', to='teams.teammember')),
            ],
            options={
                'db_table': 'team_member_roll_periods',
                'ordering': ['-from_date', '-id'],
            },
        ),
    ]
