# Generated by Django 6.0.4 on 2026-04-15 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('teams', '0002_teammemberqualificationperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberGradePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_team_member_grade_periods', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_member_periods', to='grades.grade')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_periods', to='teams.teammember')),
            ],
            options={
                'db_table': 'team_member_grade_periods',
                'ordering': ['-from_date', '-id'],
            },
        ),
    ]
