# Generated by Django 6.0.4 on 2026-04-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teammember_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
