# Generated by Django 6.0.4 on 2026-04-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('udins_source', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Udin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udin', models.CharField(max_length=60, unique=True)),
                ('mrn', models.CharField(blank=True, default='', max_length=30)),
                ('firm', models.CharField(blank=True, default='', max_length=255)),
                ('document_type', models.CharField(blank=True, default='', max_length=120)),
                ('document_sub_type', models.CharField(blank=True, default='', max_length=120)),
                ('document_description', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_signing_of_document', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('is_manual', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_udins', to=settings.AUTH_USER_MODEL)),
                ('source_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udins', to='udins_source.udinsource')),
            ],
            options={
                'db_table': 'udins',
                'ordering': ['-created_on', '-id'],
            },
        ),
    ]
