# Generated by Django 6.0.4 on 2026-04-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_chartofaccount'),
        ('udins', '0002_udin_ay_fy_udin_created_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udin',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='udins', to='config.client'),
        ),
        migrations.AddField(
            model_name='udin',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='udin',
            name='inv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='udin',
            name='inv_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
