# Generated by Django 6.0.4 on 2026-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udins', '0003_udin_client_udin_create_date_udin_inv_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udin',
            name='is_invoiced',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
