# Generated by Django 6.0.4 on 2026-04-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_service_code'),
        ('udins', '0004_udin_is_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='udin',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='udins', to='services.service'),
        ),
    ]
