# Generated by Django 6.0.4 on 2026-04-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udins', '0005_udin_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='udin',
            name='inv_tv_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Inv TV amt'),
        ),
    ]
