# Generated by Django 6.0.4 on 2026-04-29 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_chartofaccount'),
        ('services', '0002_alter_service_service_code'),
        ('udins', '0006_udin_inv_tv_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_fee_rates', to='config.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_fee_rates', to='services.service')),
            ],
            options={
                'db_table': 'udins_certification_fee_rates',
                'ordering': ['client__client_name', 'service__service_desc'],
                'constraints': [models.UniqueConstraint(fields=('client', 'service'), name='uniq_udins_cert_fee_client_service')],
            },
        ),
    ]
