# Generated by Django 6.0.4 on 2026-04-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udins', '0007_certificationfeerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='udin',
            name='service_remarks',
            field=models.TextField(blank=True, default='', help_text='User-entered notes for this UDIN in addition to the master Service record.'),
        ),
    ]
