# Generated by Django 6.0.4 on 2026-06-14 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_clientdocument'),
        ('services', '0002_alter_service_service_code'),
        ('udins', '0008_udin_service_remarks'),
        ('udins_source', '0004_udin_unique_table_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='udin',
            name='udin',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='udin',
            constraint=models.UniqueConstraint(fields=('udin',), name='uq_udins_udin'),
        ),
    ]
