# Generated by Django 6.0.4 on 2026-04-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0003_alter_client_table'),
        ('fiscal_years', '0001_initial'),
        ('services', '0002_alter_service_service_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='config.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagements', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='fiscal_years.fiscalyear')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='services.service')),
            ],
            options={
                'db_table': 'engagements',
                'ordering': ['client__client_name', 'fiscal_year__fy_no', 'service__service_desc'],
            },
        ),
        migrations.CreateModel(
            name='EngagementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateField()),
                ('planned_finish', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_finish', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_schedules', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='engagements.engagement')),
            ],
            options={
                'db_table': 'engagement_schedules',
                'ordering': ['planned_start', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('client', 'fiscal_year', 'service'), name='uq_engagement_client_fy_service'),
        ),
    ]
