# Generated by Django 6.0.4 on 2026-04-15 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_divisions', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='engagements.engagement')),
            ],
            options={
                'db_table': 'engagement_divisions',
                'ordering': ['engagement__client__client_name', 'engagement__fiscal_year__fy_no', 'engagement__service__service_desc', 'division_name'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'division_name'), name='uq_engagement_division_name')],
            },
        ),
    ]
