# Generated by Django 6.0.4 on 2026-04-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_engagementdivision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_document', models.CharField(max_length=180)),
                ('document_stage', models.CharField(choices=[('pre_engagement', 'Pre-engagement'), ('post_engagement', 'Post-engagement')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_documentations', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='engagements.engagement')),
            ],
            options={
                'db_table': 'engagement_documentations',
                'ordering': ['engagement__client__client_name', 'engagement__fiscal_year__fy_no', 'engagement__service__service_desc', 'document_stage', 'standard_document'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'standard_document', 'document_stage'), name='uq_engagement_standard_document_stage')],
            },
        ),
    ]
