# Generated by Django 6.0.4 on 2026-04-15 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_engagementdocumentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementdocumentation',
            options={'ordering': ['document_stage', 'standard_document']},
        ),
        migrations.RemoveConstraint(
            model_name='engagementdocumentation',
            name='uq_engagement_standard_document_stage',
        ),
        migrations.AddConstraint(
            model_name='engagementdocumentation',
            constraint=models.UniqueConstraint(fields=('standard_document', 'document_stage'), name='uq_standard_document_stage'),
        ),
        migrations.RemoveField(
            model_name='engagementdocumentation',
            name='engagement',
        ),
    ]
