# Generated by Django 6.0.4 on 2026-04-15 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0004_alter_engagementdocumentation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementDocumentationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_documentation_maps', to=settings.AUTH_USER_MODEL)),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagement_maps', to='engagements.engagementdocumentation')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_maps', to='engagements.engagement')),
            ],
            options={
                'db_table': 'engagement_documentation_maps',
                'ordering': ['engagement__client__client_name', 'engagement__fiscal_year__fy_no', 'engagement__service__service_desc', 'documentation__document_stage', 'documentation__standard_document'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'documentation'), name='uq_engagement_documentation_map')],
            },
        ),
    ]
