# Generated by Django 6.0.4 on 2026-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0005_engagementdocumentationmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdivision',
            name='planned_finish',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='engagementdivision',
            name='planned_start',
            field=models.DateField(null=True),
        ),
    ]
