# Generated by Django 6.0.4 on 2026-04-15 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_engagementdivision_planned_finish_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementDivisionDocumentationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_division_documentation_maps', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_maps', to='engagements.engagementdivision')),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='division_maps', to='engagements.engagementdocumentation')),
            ],
            options={
                'db_table': 'engagement_division_documentation_maps',
                'ordering': ['division__engagement__client__client_name', 'division__engagement__fiscal_year__fy_no', 'division__engagement__service__service_desc', 'division__division_name', 'documentation__document_stage', 'documentation__standard_document'],
                'constraints': [models.UniqueConstraint(fields=('division', 'documentation'), name='uq_engagement_division_documentation_map')],
            },
        ),
    ]
