# Generated by Django 6.0.4 on 2026-04-16 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_clientclassification_refactor'),
        ('engagements', '0007_engagementdivisiondocumentationmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementdocumentation',
            options={'ordering': ['applicable_classification__classification_name', 'document_stage', 'standard_document']},
        ),
        migrations.RemoveConstraint(
            model_name='engagementdocumentation',
            name='uq_standard_document_stage',
        ),
        migrations.AddField(
            model_name='engagementdocumentation',
            name='applicable_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engagement_documentations', to='config.clientclassification'),
        ),
        migrations.AddConstraint(
            model_name='engagementdocumentation',
            constraint=models.UniqueConstraint(fields=('standard_document', 'document_stage', 'applicable_classification'), name='uq_standard_document_stage_classification'),
        ),
    ]
