# Generated by Django 6.0.4 on 2026-04-16 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0010_engagementdocumentation_applicable_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionWorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area_name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_areas', to='engagements.engagementdivision')),
            ],
            options={
                'db_table': 'division_work_areas',
                'ordering': ['sort_order', 'work_area_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('division', 'work_area_name'), name='uq_division_work_area_name')],
            },
        ),
        migrations.CreateModel(
            name='EngagementWorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area_name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_areas', to='engagements.engagement')),
            ],
            options={
                'db_table': 'engagement_work_areas',
                'ordering': ['sort_order', 'work_area_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'work_area_name'), name='uq_engagement_work_area_name')],
            },
        ),
    ]
