# Generated by Django 6.0.4 on 2026-04-16 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0011_work_areas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionWorkAreaPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateField()),
                ('planned_finish', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_finish', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_division_work_area_periods', to=settings.AUTH_USER_MODEL)),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='engagements.divisionworkarea')),
            ],
            options={
                'db_table': 'division_work_area_periods',
                'ordering': ['planned_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EngagementWorkAreaPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateField()),
                ('planned_finish', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_finish', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_work_area_periods', to=settings.AUTH_USER_MODEL)),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='engagements.engagementworkarea')),
            ],
            options={
                'db_table': 'engagement_work_area_periods',
                'ordering': ['planned_start', 'id'],
            },
        ),
    ]
