# Generated by Django 6.0.4 on 2026-04-16 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0012_work_area_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionworkareaperiod',
            options={'ordering': ['planned_start', 'id'], 'verbose_name': 'Division work area schedule row', 'verbose_name_plural': 'Division work area schedule rows'},
        ),
        migrations.AlterModelOptions(
            name='engagementworkareaperiod',
            options={'ordering': ['planned_start', 'id'], 'verbose_name': 'Engagement work area schedule row', 'verbose_name_plural': 'Engagement work area schedule rows'},
        ),
        migrations.AlterField(
            model_name='divisionworkareaperiod',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_division_work_area_schedule_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='divisionworkareaperiod',
            name='work_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rows', to='engagements.divisionworkarea'),
        ),
        migrations.AlterField(
            model_name='engagementworkareaperiod',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_work_area_schedule_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engagementworkareaperiod',
            name='work_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rows', to='engagements.engagementworkarea'),
        ),
    ]
