# Generated by Django 6.0.4 on 2026-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0013_work_area_schedule_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagementdocumentation",
            name="document_stage",
            field=models.CharField(
                choices=[
                    ("pre_engagement", "Pre-engagement"),
                    ("post_engagement", "Post-engagement"),
                    ("working_papers", "Engagement Working Papers"),
                ],
                max_length=20,
            ),
        ),
    ]
