# Generated by Django 6.0.4 on 2026-04-23 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0015_engagementteamassignment"),
        ("teams", "0005_teammember_work_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementDivisionTeamAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_start", models.DateField()),
                ("planned_finish", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_engagement_division_team_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="engagements.engagementdivision",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="division_assignments",
                        to="teams.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "engagement_division_team_assignments",
                "ordering": [
                    "division__engagement__client__client_name",
                    "division__engagement__fiscal_year__fy_no",
                    "division__engagement__service__service_desc",
                    "division__division_name",
                    "planned_start",
                    "team_member__first_name",
                    "team_member__last_name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("division", "team_member"),
                        name="uq_engagement_division_team_assignment",
                    )
                ],
            },
        ),
    ]
