# Generated by Django 6.0.4 on 2026-04-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0016_engagementdivisionteamassignment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="engagementteamassignment",
            name="uq_engagement_team_assignment",
        ),
        migrations.RemoveConstraint(
            model_name="engagementdivisionteamassignment",
            name="uq_engagement_division_team_assignment",
        ),
        migrations.AlterModelOptions(
            name="engagementteamassignment",
            options={
                "ordering": [
                    "engagement__client__client_name",
                    "engagement__fiscal_year__fy_no",
                    "engagement__service__service_desc",
                    "team_member__first_name",
                    "team_member__last_name",
                    "planned_start",
                    "id",
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="engagementdivisionteamassignment",
            options={
                "ordering": [
                    "division__engagement__client__client_name",
                    "division__engagement__fiscal_year__fy_no",
                    "division__engagement__service__service_desc",
                    "division__division_name",
                    "team_member__first_name",
                    "team_member__last_name",
                    "planned_start",
                    "id",
                ],
            },
        ),
    ]
