# Generated by Django 6.0.4 on 2026-04-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0018_engagementdocumentationmap_documentation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementdocumentationmap',
            options={'ordering': ['documentation_date', 'documentation__document_stage', 'documentation__standard_document', 'pk']},
        ),
    ]
