# Generated by Django 6.0.4 on 2026-04-23 17:47

import engagements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0020_engagementdocumentationmapattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementdocumentationmapattachment',
            name='file',
            field=models.FileField(upload_to=engagements.models._engagement_documentation_map_upload_to),
        ),
    ]
