# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0023_team_assignment_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagementdivision",
            name="planned_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="engagementdivision",
            name="planned_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
