# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0024_alter_engagementdivision_planned_dates_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagementworkareaperiod",
            name="planned_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="engagementworkareaperiod",
            name="planned_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="divisionworkareaperiod",
            name="planned_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="divisionworkareaperiod",
            name="planned_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
