# Generated by Django 6.0.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0026_engagementworkareadocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementWorkAreaTeamAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_notes", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_engagement_work_area_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engagement_work_area_assignments",
                        to="teams.teammember",
                    ),
                ),
                (
                    "work_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="engagements.engagementworkarea",
                    ),
                ),
            ],
            options={
                "db_table": "engagement_work_area_team_assignments",
                "ordering": [
                    "work_area__engagement__client__client_name",
                    "work_area__engagement__fiscal_year__fy_no",
                    "work_area__engagement__service__service_desc",
                    "work_area__work_area_name",
                    "team_member__first_name",
                    "team_member__last_name",
                    "team_member__code",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="engagementworkareateamassignment",
            constraint=models.UniqueConstraint(
                fields=("work_area", "team_member"),
                name="uq_engagement_work_area_team_assignment",
            ),
        ),
    ]
