# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0027_engagementworkareateamassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementworkareateamassignment",
            name="planned_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engagementworkareateamassignment",
            name="planned_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
