# Generated by Django 6.0.4 on 2026-04-24 14:27

import django.db.models.deletion
import engagements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0028_engagementworkareateamassignment_planned_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementDivisionDocumentationMapAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=engagements.models._engagement_division_documentation_map_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('document_date', models.DateField(help_text='Date of the underlying document (e.g. letter or signing date).')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagement_division_documentation_attachments', to=settings.AUTH_USER_MODEL)),
                ('documentation_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='engagements.engagementdivisiondocumentationmap')),
            ],
            options={
                'db_table': 'engagement_division_documentation_map_attachments',
                'ordering': ['-document_date', 'original_filename', 'pk'],
            },
        ),
    ]
