# Generated by Django 6.0.4 on 2026-04-24 15:01

import django.db.models.deletion
import engagements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0029_engagementdivisiondocumentationmapattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionWorkAreaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=engagements.models._division_work_area_document_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_division_work_area_documents', to=settings.AUTH_USER_MODEL)),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='engagements.divisionworkarea')),
            ],
            options={
                'db_table': 'division_work_area_documents',
                'ordering': ['-document_date', 'original_filename', 'pk'],
            },
        ),
    ]
