# Generated by Django 6.0.4 on 2026-04-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0030_divisionworkareadocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdivisiondocumentationmapattachment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='engagementdocumentationmapattachment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
