# Generated by Django 6.0.4 on 2026-04-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0031_engagementdivisiondocumentationmapattachment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementdivisiondocumentationmapattachment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='engagementdocumentationmapattachment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
