# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0032_alter_engagementdivisiondocumentationmapattachment_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagementdocumentation",
            name="document_stage",
            field=models.CharField(
                choices=[
                    ("pre_engagement", "Pre-engagement"),
                    ("post_engagement", "Post-engagement"),
                    ("working_papers", "Engagement Working Papers"),
                    ("engagement_planning", "Engagement Planning"),
                    ("engagement_conclusion", "Engagement Conclusion"),
                ],
                max_length=30,
            ),
        ),
    ]
