# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0033_engagementdocumentation_planning_conclusion_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="engagementdivision",
            name="status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="engagementworkarea",
            name="status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="divisionworkarea",
            name="status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
