# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0034_status_fields_for_engagement_entities"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementdivision",
            name="actual_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engagementdivision",
            name="actual_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
