# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0035_engagementdivision_actual_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="divisionworkarea",
            name="closure_source",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="divisionworkareaperiod",
            name="closure_source",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="engagementdivision",
            name="closure_source",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="engagementworkarea",
            name="closure_source",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="engagementworkareaperiod",
            name="closure_source",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
