# Generated by Django 6.0.4 on 2026-04-26 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0036_closure_source_audit_fields'),
        ('teams', '0005_teammember_work_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('adjusted', 'Adjusted')], default='open', max_length=20)),
                ('close_source', models.CharField(blank=True, choices=[('', 'N/A'), ('user_stop', 'User stop'), ('auto_switch', 'Auto switch'), ('auto_day_close', 'Auto day close'), ('admin_fix', 'Admin fix')], default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='engagements.engagementdivision')),
                ('division_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='engagements.divisionworkarea')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='engagements.engagement')),
                ('engagement_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='engagements.engagementworkarea')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_time_sessions', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_sessions', to='teams.teammember')),
            ],
            options={
                'db_table': 'time_sessions',
                'ordering': ['-started_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('engagement_work_area__isnull', True), ('division_work_area__isnull', True), _connector='OR'), name='ck_time_session_one_work_area_type'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ck_time_session_ended_after_started'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('team_member',), name='uq_time_session_one_open_per_member')],
            },
        ),
    ]
