# Generated by Django 6.0.4 on 2026-04-26 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0037_timesession'),
        ('teams', '0005_teammember_work_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionWorkAreaTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_finish', models.DateField(blank=True, null=True)),
                ('assignment_notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_division_work_area_assignments', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='division_work_area_assignments', to='teams.teammember')),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='engagements.divisionworkarea')),
            ],
            options={
                'db_table': 'division_work_area_team_assignments',
                'ordering': ['work_area__division__engagement__client__client_name', 'work_area__division__engagement__fiscal_year__fy_no', 'work_area__division__engagement__service__service_desc', 'work_area__division__division_name', 'work_area__work_area_name', 'team_member__first_name', 'team_member__last_name', 'team_member__code'],
                'constraints': [models.UniqueConstraint(fields=('work_area', 'team_member'), name='uq_division_work_area_team_assignment')],
            },
        ),
    ]
