# Generated by Django 6.0.4 on 2026-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0038_divisionworkareateamassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesession',
            name='task_description',
            field=models.CharField(blank=True, default='', help_text='What you are doing on this engagement/division/work area (free text).', max_length=500),
        ),
    ]
