# Generated by Django 6.0.4 on 2026-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0040_divisionworkareaconfirmationmaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionworkareadocument',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
