# Generated by Django 6.0.4 on 2026-05-10 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0054_auditqueryattachment'),
        ('services', '0002_alter_service_service_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEngagementChecklistWorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_engagement_checklist_work_areas', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_checklist_work_areas', to='services.service')),
            ],
            options={
                'db_table': 'service_engagement_checklist_work_areas',
                'ordering': ['service', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEngagementChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_text', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_engagement_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='engagements.serviceengagementchecklistworkarea')),
            ],
            options={
                'db_table': 'service_engagement_checklist_items',
                'ordering': ['work_area', 'sort_order', 'id'],
            },
        ),
    ]
