# Generated by Django 6.0.4 on 2026-05-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0056_work_area_service_checklist_template_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionworkareastatusremark',
            options={'ordering': ['-remark_date', '-created_on', '-id']},
        ),
    ]
