# Generated by Django 6.0.4 on 2026-05-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0057_alter_divisionworkareastatusremark_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionworkarea',
            name='service_checklist_work_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_work_area_instances', to='engagements.serviceengagementchecklistworkarea'),
        ),
        migrations.AlterField(
            model_name='engagementworkarea',
            name='service_checklist_work_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_work_area_instances', to='engagements.serviceengagementchecklistworkarea'),
        ),
    ]
