# Generated by Django 6.0.4 on 2026-05-10 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0058_alter_service_checklist_work_area_on_delete_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionworkarea',
            name='service_checklist_work_area',
            field=models.ForeignKey(blank=True, help_text='Optional pointer to the service checklist template used when this row was created—convenience only; not for data integrity (cleared if the template is deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_work_area_instances', to='engagements.serviceengagementchecklistworkarea'),
        ),
        migrations.AlterField(
            model_name='engagementworkarea',
            name='service_checklist_work_area',
            field=models.ForeignKey(blank=True, help_text='Optional pointer to the service checklist template used when this row was created—convenience only; not for data integrity (cleared if the template is deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_work_area_instances', to='engagements.serviceengagementchecklistworkarea'),
        ),
    ]
