# Generated by Django 6.0.4 on 2026-05-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0059_service_checklist_work_area_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionworkarea',
            name='service_checklist_work_area',
            field=models.ForeignKey(blank=True, help_text='Optional link to the Service engagement checklist work-area template (setup) used when this row was picked there—convenience for that pointer only; cleared if that template is deleted. Other masters are unrelated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_work_area_instances', to='engagements.serviceengagementchecklistworkarea'),
        ),
        migrations.AlterField(
            model_name='engagementworkarea',
            name='service_checklist_work_area',
            field=models.ForeignKey(blank=True, help_text='Optional link to the Service engagement checklist work-area template (setup) used when this row was picked there—convenience for that pointer only; cleared if that template is deleted. Other masters are unrelated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_work_area_instances', to='engagements.serviceengagementchecklistworkarea'),
        ),
    ]
