# Generated by Django 6.0.4 on 2026-05-11 05:31

import engagements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0060_alter_divisionworkarea_service_checklist_work_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdocumentation',
            name='word_template',
            field=models.FileField(blank=True, help_text='Optional Word template (.doc or .docx) for this standard document.', null=True, upload_to=engagements.models._engagement_documentation_word_template_upload_to),
        ),
    ]
