# Generated by Django 6.0.4 on 2026-05-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0061_engagement_documentation_word_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditquery',
            name='service_checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_queries', to='engagements.serviceengagementchecklistitem'),
        ),
        migrations.AddField(
            model_name='divisionworkarea',
            name='monetary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional monetary amount for this work area (from work area notes).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='divisionworkarea',
            name='monetary_amount_unit',
            field=models.CharField(blank=True, default='lakhs', help_text='Unit for monetary_amount (lakhs, rs, crores).', max_length=20),
        ),
        migrations.AddField(
            model_name='engagementworkarea',
            name='monetary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional monetary amount for this work area (from work area notes).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='engagementworkarea',
            name='monetary_amount_unit',
            field=models.CharField(blank=True, default='lakhs', help_text='Unit for monetary_amount (lakhs, rs, crores).', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditquery',
            name='entry_type',
            field=models.CharField(choices=[('query', 'Query'), ('remark', 'Remark'), ('status', 'Status')], default='query', max_length=20),
        ),
    ]
