# Generated by Django 6.0.4 on 2026-05-11 11:55

import django.db.models.deletion
import engagements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0062_work_area_amount_and_auditquery_checklist_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('audit_methodology', 'Audit methodology'), ('tax', 'Tax'), ('it_tools', 'IT & tools'), ('firm_policies', 'Firm policies'), ('templates_non_client', 'Templates (non-client-specific)'), ('external_standards', 'External standards & circulars'), ('general', 'General / other')], db_index=True, default='general', max_length=40)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated keywords for search (e.g. SA 230, sampling, Excel).', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items stay in the database but are hidden from the default list.')),
                ('file', models.FileField(upload_to=engagements.models._firm_reference_document_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_firm_reference_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firm_reference_documents',
                'ordering': ['category', 'title', 'pk'],
            },
        ),
    ]
