# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engagements", "0064_firm_reference_document_category_freetext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmreferencedocument",
            name="category",
            field=models.CharField(
                db_index=True,
                default="General / other",
                help_text="Use a suggested name or type your own; this is shown in lists and search.",
                max_length=100,
            ),
        ),
    ]
