# Generated by Django 6.0.4 on 2026-05-11 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0065_alter_firmreferencedocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional engagement-level fee (e.g. audit fee). Certification engagements may use per-certificate amounts later.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
