# Generated by Django 6.0.4 on 2026-06-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0069_auditquery_status_to_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementworkareadocument',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
