# Generated by Django 6.0.4 on 2026-06-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0070_engagementworkareadocument_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionworkareadocument',
            name='document_reference_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='engagementworkareadocument',
            name='document_reference_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
