# Generated by Django 6.0.4 on 2026-06-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0071_divisionworkareadocument_document_reference_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionworkarea',
            name='documentation',
            field=models.ForeignKey(blank=True, help_text='Broader documentation this work area falls under.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='division_work_areas', to='engagements.engagementdocumentation'),
        ),
        migrations.AddField(
            model_name='engagementworkarea',
            name='documentation',
            field=models.ForeignKey(blank=True, help_text='Broader documentation this work area falls under.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engagement_work_areas', to='engagements.engagementdocumentation'),
        ),
    ]
