# Generated by Django 6.0.4 on 2026-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0072_divisionworkarea_documentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditqueryattachment',
            name='document_reference_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
