# Generated by Django 6.0.4 on 2026-08-13 12:50

import django.db.models.deletion
import engagements.work_documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0073_auditqueryattachment_document_reference_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('engagement', 'Engagement'), ('division', 'Division')], max_length=20)),
                ('source_type', models.CharField(choices=[('audit_query', 'Audit query'), ('work_area', 'Work area document'), ('documentation_map', 'Documentation map')], max_length=30)),
                ('classification', models.CharField(choices=[('blank_template', 'Blank template'), ('other', 'Other')], default='other', max_length=20)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('document_reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=engagements.work_documents.models._work_document_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('legacy_table', models.CharField(blank=True, default='', max_length=100)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('audit_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_documents', to='engagements.auditquery')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_documents', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_documents', to='engagements.engagementdivision')),
                ('division_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_documents', to='engagements.divisionworkarea')),
                ('documentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_documents', to='engagements.engagementdocumentation')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_documents', to='engagements.engagement')),
                ('engagement_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_documents', to='engagements.engagementworkarea')),
            ],
            options={
                'db_table': 'work_documents',
                'ordering': ['-created_on', 'original_filename', 'pk'],
                'indexes': [models.Index(fields=['scope_type', 'source_type', 'classification'], name='work_docume_scope_t_63b9dc_idx'), models.Index(fields=['legacy_table', 'legacy_id'], name='work_docume_legacy__4429e9_idx')],
            },
        ),
    ]
